"""
统一错误码体系

错误码分类：
- ASSET_* : 资产相关
- CONFIG_* : 配置相关
- COLLECTOR_* : 采集器相关
- STATE_* : 状态相关
- EVENT_* : 事件相关
- ALERT_* : 告警相关
- LOG_* : 日志相关
- POLICY_* : 策略相关
- AUTOMATION_* : 自动化相关
- AIOPS_* : AIops相关
- TICKET_* : 工单相关
- KNOWLEDGE_* : 知识相关
- AUTH_* : 认证相关
- SYSTEM_* : 系统相关
"""

from enum import Enum


class ErrorCode(str, Enum):
    """错误码枚举"""

    # 成功
    OK = "OK"

    # ========== ASSET_* ==========
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    ASSET_ALREADY_EXISTS = "ASSET_ALREADY_EXISTS"
    ASSET_CREATE_FAILED = "ASSET_CREATE_FAILED"
    ASSET_UPDATE_FAILED = "ASSET_UPDATE_FAILED"
    ASSET_DELETE_FAILED = "ASSET_DELETE_FAILED"
    ASSET_VALIDATION_FAILED = "ASSET_VALIDATION_FAILED"
    ASSET_BINDING_FAILED = "ASSET_BINDING_FAILED"

    # ========== CONFIG_* ==========
    CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND"
    CONFIG_ALREADY_EXISTS = "CONFIG_ALREADY_EXISTS"
    CONFIG_CREATE_FAILED = "CONFIG_CREATE_FAILED"
    CONFIG_UPDATE_FAILED = "CONFIG_UPDATE_FAILED"
    CONFIG_DELETE_FAILED = "CONFIG_DELETE_FAILED"
    CONFIG_VERSION_CONFLICT = "CONFIG_VERSION_CONFLICT"
    CONFIG_RELEASE_FAILED = "CONFIG_RELEASE_FAILED"
    CONFIG_ROLLBACK_FAILED = "CONFIG_ROLLBACK_FAILED"

    # ========== COLLECTOR_* ==========
    COLLECTOR_NOT_FOUND = "COLLECTOR_NOT_FOUND"
    COLLECTOR_CONNECTION_FAILED = "COLLECTOR_CONNECTION_FAILED"
    COLLECTOR_COLLECT_FAILED = "COLLECTOR_COLLECT_FAILED"
    COLLECTOR_TIMEOUT = "COLLECTOR_TIMEOUT"
    COLLECTOR_UNSUPPORTED_PROTOCOL = "COLLECTOR_UNSUPPORTED_PROTOCOL"

    # ========== STATE_* ==========
    STATE_NOT_FOUND = "STATE_NOT_FOUND"
    STATE_UPDATE_FAILED = "STATE_UPDATE_FAILED"
    STATE_HISTORY_NOT_FOUND = "STATE_HISTORY_NOT_FOUND"

    # ========== EVENT_* ==========
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_CREATE_FAILED = "EVENT_CREATE_FAILED"
    EVENT_CORRELATION_FAILED = "EVENT_CORRELATION_FAILED"

    # ========== ALERT_* ==========
    ALERT_NOT_FOUND = "ALERT_NOT_FOUND"
    ALERT_CREATE_FAILED = "ALERT_CREATE_FAILED"
    ALERT_UPDATE_FAILED = "ALERT_UPDATE_FAILED"
    ALERT_RESOLVE_FAILED = "ALERT_RESOLVE_FAILED"
    ALERT_TRANSFER_FAILED = "ALERT_TRANSFER_FAILED"
    ALERT_SUPPRESS_FAILED = "ALERT_SUPPRESS_FAILED"
    ALERT_SUPPRESSED = "ALERT_SUPPRESSED"
    ALERT_ESCALATE_FAILED = "ALERT_ESCALATE_FAILED"
    ALERT_CONSOLIDATION_FAILED = "ALERT_CONSOLIDATION_FAILED"
    ALERT_RULE_NOT_FOUND = "ALERT_RULE_NOT_FOUND"
    ALERT_RULE_CREATE_FAILED = "ALERT_RULE_CREATE_FAILED"
    ALERT_RULE_UPDATE_FAILED = "ALERT_RULE_UPDATE_FAILED"
    ALERT_RULE_DELETE_FAILED = "ALERT_RULE_DELETE_FAILED"
    ALERT_TRIGGER_FAILED = "ALERT_TRIGGER_FAILED"
    ALERT_EVALUATION_FAILED = "ALERT_EVALUATION_FAILED"

    # ========== LOG_* ==========
    LOG_NOT_FOUND = "LOG_NOT_FOUND"
    LOG_CREATE_FAILED = "LOG_CREATE_FAILED"
    LOG_QUERY_FAILED = "LOG_QUERY_FAILED"
    LOG_CONFIG_NOT_FOUND = "LOG_CONFIG_NOT_FOUND"
    LOG_CONFIG_UPDATE_FAILED = "LOG_CONFIG_UPDATE_FAILED"
    LOG_INDEX_NOT_FOUND = "LOG_INDEX_NOT_FOUND"
    LOG_INDEX_CREATE_FAILED = "LOG_INDEX_CREATE_FAILED"
    LOG_INDEX_DELETE_FAILED = "LOG_INDEX_DELETE_FAILED"
    LOG_ACCESS_CONFIG_NOT_FOUND = "LOG_ACCESS_CONFIG_NOT_FOUND"
    LOG_ACCESS_CONFIG_UPDATE_FAILED = "LOG_ACCESS_CONFIG_UPDATE_FAILED"
    LOG_GROUP_NOT_FOUND = "LOG_GROUP_NOT_FOUND"
    LOG_ITEM_NOT_FOUND = "LOG_ITEM_NOT_FOUND"

    # ========== POLICY_* ==========
    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    POLICY_ALREADY_EXISTS = "POLICY_ALREADY_EXISTS"
    POLICY_CREATE_FAILED = "POLICY_CREATE_FAILED"
    POLICY_UPDATE_FAILED = "POLICY_UPDATE_FAILED"
    POLICY_DELETE_FAILED = "POLICY_DELETE_FAILED"
    POLICY_SIMULATE_FAILED = "POLICY_SIMULATE_FAILED"
    POLICY_CONFLICT = "POLICY_CONFLICT"
    POLICY_HIT_FAILED = "POLICY_HIT_FAILED"

    # ========== AUTOMATION_* ==========
    AUTOMATION_NOT_FOUND = "AUTOMATION_NOT_FOUND"
    AUTOMATION_CREATE_FAILED = "AUTOMATION_CREATE_FAILED"
    AUTOMATION_UPDATE_FAILED = "AUTOMATION_UPDATE_FAILED"
    AUTOMATION_DELETE_FAILED = "AUTOMATION_DELETE_FAILED"
    AUTOMATION_EXECUTE_FAILED = "AUTOMATION_EXECUTE_FAILED"
    AUTOMATION_ROLLBACK_FAILED = "AUTOMATION_ROLLBACK_FAILED"
    AUTOMATION_DRYRUN_FAILED = "AUTOMATION_DRYRUN_FAILED"
    AUTOMATION_APPROVAL_REQUIRED = "AUTOMATION_APPROVAL_REQUIRED"
    AUTOMATION_RISK_TOO_HIGH = "AUTOMATION_RISK_TOO_HIGH"
    AUTOMATION_LOCK_FAILED = "AUTOMATION_LOCK_FAILED"
    AUTOMATION_VERIFY_FAILED = "AUTOMATION_VERIFY_FAILED"

    # ========== AIOPS_* ==========
    AIOPS_ANALYSIS_FAILED = "AIOPS_ANALYSIS_FAILED"
    AIOPS_CONTEXT_BUILD_FAILED = "AIOPS_CONTEXT_BUILD_FAILED"
    AIOPS_LLM_UNAVAILABLE = "AIOPS_LLM_UNAVAILABLE"
    AIOPS_TOOL_FORBIDDEN = "AIOPS_TOOL_FORBIDDEN"

    # ========== TICKET_* ==========
    TICKET_NOT_FOUND = "TICKET_NOT_FOUND"
    TICKET_CREATE_FAILED = "TICKET_CREATE_FAILED"
    TICKET_UPDATE_FAILED = "TICKET_UPDATE_FAILED"
    TICKET_ASSIGN_FAILED = "TICKET_ASSIGN_FAILED"
    TICKET_APPROVE_FAILED = "TICKET_APPROVE_FAILED"
    TICKET_REJECT_FAILED = "TICKET_REJECT_FAILED"
    TICKET_CLOSE_FAILED = "TICKET_CLOSE_FAILED"

    # ========== KNOWLEDGE_* ==========
    KNOWLEDGE_NOT_FOUND = "KNOWLEDGE_NOT_FOUND"
    KNOWLEDGE_CREATE_FAILED = "KNOWLEDGE_CREATE_FAILED"
    KNOWLEDGE_UPDATE_FAILED = "KNOWLEDGE_UPDATE_FAILED"
    KNOWLEDGE_DELETE_FAILED = "KNOWLEDGE_DELETE_FAILED"
    KNOWLEDGE_REVIEW_FAILED = "KNOWLEDGE_REVIEW_FAILED"
    KNOWLEDGE_APPROVE_FAILED = "KNOWLEDGE_APPROVE_FAILED"
    KNOWLEDGE_REJECT_FAILED = "KNOWLEDGE_REJECT_FAILED"

    # ========== AUTH_* ==========
    AUTH_FAILED = "AUTH_FAILED"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_PERMISSION_DENIED = "AUTH_PERMISSION_DENIED"
    AUTH_CREDENTIAL_INVALID = "AUTH_CREDENTIAL_INVALID"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    AUTH_LDAP_FAILED = "AUTH_LDAP_FAILED"

    # ========== SYSTEM_* ==========
    SYSTEM_INTERNAL_ERROR = "SYSTEM_INTERNAL_ERROR"
    SYSTEM_DATABASE_ERROR = "SYSTEM_DATABASE_ERROR"
    SYSTEM_REDIS_ERROR = "SYSTEM_REDIS_ERROR"
    SYSTEM_QUEUE_ERROR = "SYSTEM_QUEUE_ERROR"
    SYSTEM_VALIDATION_ERROR = "SYSTEM_VALIDATION_ERROR"
    SYSTEM_RESOURCE_NOT_FOUND = "SYSTEM_RESOURCE_NOT_FOUND"
    SYSTEM_RESOURCE_CONFLICT = "SYSTEM_RESOURCE_CONFLICT"
    SYSTEM_RATE_LIMITED = "SYSTEM_RATE_LIMITED"
    SYSTEM_UNAVAILABLE = "SYSTEM_UNAVAILABLE"


# HTTP 状态码映射
ERROR_CODE_TO_HTTP_STATUS = {
    # 4xx
    "OK": 200,
    "ASSET_NOT_FOUND": 404,
    "ASSET_ALREADY_EXISTS": 409,
    "ASSET_VALIDATION_FAILED": 422,
    "CONFIG_NOT_FOUND": 404,
    "CONFIG_ALREADY_EXISTS": 409,
    "CONFIG_VERSION_CONFLICT": 409,
    "COLLECTOR_NOT_FOUND": 404,
    "COLLECTOR_UNSUPPORTED_PROTOCOL": 422,
    "STATE_NOT_FOUND": 404,
    "EVENT_NOT_FOUND": 404,
    "ALERT_NOT_FOUND": 404,
    "LOG_NOT_FOUND": 404,
    "POLICY_NOT_FOUND": 404,
    "POLICY_ALREADY_EXISTS": 409,
    "POLICY_CONFLICT": 409,
    "AUTOMATION_NOT_FOUND": 404,
    "AUTOMATION_APPROVAL_REQUIRED": 403,
    "AUTOMATION_RISK_TOO_HIGH": 403,
    "AIOPS_TOOL_FORBIDDEN": 403,
    "TICKET_NOT_FOUND": 404,
    "AUTH_FAILED": 401,
    "AUTH_TOKEN_EXPIRED": 401,
    "AUTH_TOKEN_INVALID": 401,
    "AUTH_PERMISSION_DENIED": 403,
    "AUTH_CREDENTIAL_INVALID": 401,
    "AUTH_USER_NOT_FOUND": 401,
    "AUTH_LDAP_FAILED": 401,
    "SYSTEM_VALIDATION_ERROR": 422,
    "SYSTEM_RESOURCE_NOT_FOUND": 404,
    "SYSTEM_RESOURCE_CONFLICT": 409,
    "SYSTEM_RATE_LIMITED": 429,
    # 5xx
    "SYSTEM_INTERNAL_ERROR": 500,
    "SYSTEM_DATABASE_ERROR": 500,
    "SYSTEM_REDIS_ERROR": 500,
    "SYSTEM_QUEUE_ERROR": 500,
    "ASSET_CREATE_FAILED": 500,
    "ASSET_UPDATE_FAILED": 500,
    "ASSET_DELETE_FAILED": 500,
    "ASSET_BINDING_FAILED": 500,
    "CONFIG_CREATE_FAILED": 500,
    "CONFIG_UPDATE_FAILED": 500,
    "CONFIG_DELETE_FAILED": 500,
    "CONFIG_RELEASE_FAILED": 500,
    "CONFIG_ROLLBACK_FAILED": 500,
    "COLLECTOR_CONNECTION_FAILED": 500,
    "COLLECTOR_COLLECT_FAILED": 500,
    "COLLECTOR_TIMEOUT": 504,
    "STATE_UPDATE_FAILED": 500,
    "STATE_HISTORY_NOT_FOUND": 404,
    "EVENT_CREATE_FAILED": 500,
    "EVENT_CORRELATION_FAILED": 500,
    "ALERT_CREATE_FAILED": 500,
    "ALERT_UPDATE_FAILED": 500,
    "ALERT_RESOLVE_FAILED": 500,
    "ALERT_TRANSFER_FAILED": 500,
    "ALERT_SUPPRESS_FAILED": 500,
    "ALERT_SUPPRESSED": 400,
    "ALERT_ESCALATE_FAILED": 500,
    "ALERT_CONSOLIDATION_FAILED": 500,
    "ALERT_RULE_NOT_FOUND": 404,
    "ALERT_RULE_CREATE_FAILED": 500,
    "ALERT_RULE_UPDATE_FAILED": 500,
    "ALERT_RULE_DELETE_FAILED": 500,
    "ALERT_TRIGGER_FAILED": 500,
    "ALERT_EVALUATION_FAILED": 500,
    "LOG_CREATE_FAILED": 500,
    "LOG_QUERY_FAILED": 500,
    "LOG_CONFIG_NOT_FOUND": 404,
    "LOG_CONFIG_UPDATE_FAILED": 500,
    "LOG_INDEX_NOT_FOUND": 404,
    "LOG_INDEX_CREATE_FAILED": 500,
    "LOG_INDEX_DELETE_FAILED": 500,
    "LOG_ACCESS_CONFIG_NOT_FOUND": 404,
    "LOG_ACCESS_CONFIG_UPDATE_FAILED": 500,
    "LOG_GROUP_NOT_FOUND": 404,
    "LOG_ITEM_NOT_FOUND": 404,
    "POLICY_CREATE_FAILED": 500,
    "POLICY_UPDATE_FAILED": 500,
    "POLICY_DELETE_FAILED": 500,
    "POLICY_SIMULATE_FAILED": 500,
    "POLICY_HIT_FAILED": 500,
    "AUTOMATION_CREATE_FAILED": 500,
    "AUTOMATION_UPDATE_FAILED": 500,
    "AUTOMATION_DELETE_FAILED": 500,
    "AUTOMATION_EXECUTE_FAILED": 500,
    "AUTOMATION_ROLLBACK_FAILED": 500,
    "AUTOMATION_DRYRUN_FAILED": 500,
    "AUTOMATION_LOCK_FAILED": 500,
    "AUTOMATION_VERIFY_FAILED": 500,
    "AIOPS_ANALYSIS_FAILED": 500,
    "AIOPS_CONTEXT_BUILD_FAILED": 500,
    "AIOPS_LLM_UNAVAILABLE": 503,
    "TICKET_CREATE_FAILED": 500,
    "TICKET_UPDATE_FAILED": 500,
    "TICKET_ASSIGN_FAILED": 500,
    "TICKET_APPROVE_FAILED": 500,
    "TICKET_REJECT_FAILED": 500,
    "TICKET_CLOSE_FAILED": 500,
    "KNOWLEDGE_NOT_FOUND": 404,
    "KNOWLEDGE_CREATE_FAILED": 500,
    "KNOWLEDGE_UPDATE_FAILED": 500,
    "KNOWLEDGE_DELETE_FAILED": 500,
    "KNOWLEDGE_REVIEW_FAILED": 500,
    "KNOWLEDGE_APPROVE_FAILED": 500,
    "KNOWLEDGE_REJECT_FAILED": 500,
    "SYSTEM_UNAVAILABLE": 503,
}


def get_http_status(error_code: str) -> int:
    """根据错误码获取 HTTP 状态码"""
    return ERROR_CODE_TO_HTTP_STATUS.get(error_code, 500)
